name: Run tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r <(grep -v '^pywin32==' requirements.txt)  # Skip pywin32 on non-Windows
    - name: Run tests
      run: |
        echo "No tests yet"